config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :seller_profiles
  resources :enquiries
  devise_for :users, controllers: { registrations: "registrations"}
  root 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
  validates :name, :email, :message, presence: true
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)

    respond_to do |format|
      if @enquiry.save
        EnquiryMailer.response(@enquiry.id).deliver_now
        EnquiryMailer.received(@enquiry.id).deliver_now
        format.html { redirect_to root_path, notice: 'Your Enquiry has been sent' }
        format.json { render :show, status: :created, location: @enquiry }
      else
        format.html { render :new }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiries/1
  # PATCH/PUT /enquiries/1.json
  def update
    respond_to do |format|
      if @enquiry.update(enquiry_params)
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry }
      else
        format.html { render :edit }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :phone, :subject, :message)
    end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_form.html.erb
<%= simple_form_for(@enquiry) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">

      <div class="col-md-4">
            <%= f.input :name, label: false, placeholder: "Your name" %>
      </div>

      <div class="col-md-4">
            <%= f.input :email, label: false, placeholder: "Your email" %>
      </div>
      <div class="col-md-4">
            <%= f.input :phone, label: false, placeholder: "Your phone" %>
      </div>
    </div>

    <%= f.input :subject, label: false, collection: ['General enquiry', 'Website error'], prompt: 'Choose reason for enquiry' %>

    <%= f.input :message, label: false, placeholder: "Enter Your message", input_html: {rows: 5} %>

  </div>

  <div class="form-actions">
    <button type="submit" name="button" class = "btn btn-primary">
      <i class = "fa fa-paper-plane"></i> Send message
    </button>

    <!-- <%= f.submit "Create Enquiry", class: "btn btn-primary"%> -->
  </div>

<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enquiries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enquiries.each do |enquiry| %>
      <tr>
        <td><%= enquiry.name %></td>
        <td><%= enquiry.email %></td>
        <td><%= enquiry.phone %></td>
        <td><%= enquiry.subject %></td>
        <td><%= enquiry.message %></td>
        <td><%= link_to 'Show', enquiry %></td>
        <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<h1>New Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Back', enquiries_path %>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enquiry.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @enquiry.phone %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @enquiry.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @enquiry.message %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>